export const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
      <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
      <url>
        <loc>https://www.theaipaper.com/</loc>
        <changefreq>monthly</changefreq>
        <priority>1.0</priority>
      </url>
      <url>
              <loc>https://www.theaipaper.com/p/10-ways-to-use-up-leftover-cooked-rice</loc>
              <lastmod>2022-09-30T14:52:28.704Z</lastmod>
              <changefreq>monthly</changefreq>
              <priority>1.0</priority>
            </url><url>
              <loc>https://www.theaipaper.com/es/p/10-maneras-de-usar-el-arroz-cocido-sobrante</loc>
              <lastmod>2022-09-30T14:52:28.704Z</lastmod>
              <changefreq>monthly</changefreq>
              <priority>1.0</priority>
            </url><url>
              <loc>https://www.theaipaper.com/p/how-to-make-the-perfect-grilled-cheese-sandwich</loc>
              <lastmod>2022-09-30T14:52:28.461Z</lastmod>
              <changefreq>monthly</changefreq>
              <priority>1.0</priority>
            </url><url>
              <loc>https://www.theaipaper.com/es/p/como-hacer-el-sandwich-de-queso-a-la-parrilla-perfecto</loc>
              <lastmod>2022-09-30T14:52:28.461Z</lastmod>
              <changefreq>monthly</changefreq>
              <priority>1.0</priority>
            </url><url>
              <loc>https://www.theaipaper.com/p/the-best-way-to-cook-eggs-scrambled-poached-or-sunny-side-up</loc>
              <lastmod>2022-09-30T14:52:28.211Z</lastmod>
              <changefreq>monthly</changefreq>
              <priority>1.0</priority>
            </url><url>
              <loc>https://www.theaipaper.com/es/p/la-mejor-manera-de-cocinar-huevos-revueltos-escalfados-o-soleados</loc>
              <lastmod>2022-09-30T14:52:28.211Z</lastmod>
              <changefreq>monthly</changefreq>
              <priority>1.0</priority>
            </url><url>
              <loc>https://www.theaipaper.com/p/5-easy-tips-for-making-better-pasta-dishes</loc>
              <lastmod>2022-09-30T14:52:27.968Z</lastmod>
              <changefreq>monthly</changefreq>
              <priority>1.0</priority>
            </url><url>
              <loc>https://www.theaipaper.com/es/p/5-sencillos-consejos-para-hacer-mejores-platos-de-pasta</loc>
              <lastmod>2022-09-30T14:52:27.968Z</lastmod>
              <changefreq>monthly</changefreq>
              <priority>1.0</priority>
            </url><url>
              <loc>https://www.theaipaper.com/p/comfort-food-recipes-to-warm-your-soul</loc>
              <lastmod>2022-09-30T14:52:27.720Z</lastmod>
              <changefreq>monthly</changefreq>
              <priority>1.0</priority>
            </url><url>
              <loc>https://www.theaipaper.com/es/p/recetas-de-comida-reconfortante-para-calentar-tu-alma</loc>
              <lastmod>2022-09-30T14:52:27.720Z</lastmod>
              <changefreq>monthly</changefreq>
              <priority>1.0</priority>
            </url><url>
              <loc>https://www.theaipaper.com/p/one-pot-wonders-easy-recipes-for-busy-weeknights</loc>
              <lastmod>2022-09-30T14:52:27.468Z</lastmod>
              <changefreq>monthly</changefreq>
              <priority>1.0</priority>
            </url><url>
              <loc>https://www.theaipaper.com/es/p/maravillas-de-una-olla-recetas-faciles-para-noches-ocupadas-entre-semana</loc>
              <lastmod>2022-09-30T14:52:27.468Z</lastmod>
              <changefreq>monthly</changefreq>
              <priority>1.0</priority>
            </url><url>
              <loc>https://www.theaipaper.com/p/from-soup-to-nuts-the-best-recipes-for-winter</loc>
              <lastmod>2022-09-30T14:52:27.203Z</lastmod>
              <changefreq>monthly</changefreq>
              <priority>1.0</priority>
            </url><url>
              <loc>https://www.theaipaper.com/es/p/de-la-sopa-a-las-nueces-las-mejores-recetas-para-el-invierno</loc>
              <lastmod>2022-09-30T14:52:27.203Z</lastmod>
              <changefreq>monthly</changefreq>
              <priority>1.0</priority>
            </url><url>
              <loc>https://www.theaipaper.com/p/the-ultimate-guide-to-making-a-perfect-pie-crust</loc>
              <lastmod>2022-09-30T14:52:26.960Z</lastmod>
              <changefreq>monthly</changefreq>
              <priority>1.0</priority>
            </url><url>
              <loc>https://www.theaipaper.com/es/p/la-guia-definitiva-para-hacer-una-masa-de-pastel-perfecta</loc>
              <lastmod>2022-09-30T14:52:26.960Z</lastmod>
              <changefreq>monthly</changefreq>
              <priority>1.0</priority>
            </url><url>
              <loc>https://www.theaipaper.com/p/how-to-make-the-perfect-roast-chicken</loc>
              <lastmod>2022-09-30T14:52:26.714Z</lastmod>
              <changefreq>monthly</changefreq>
              <priority>1.0</priority>
            </url><url>
              <loc>https://www.theaipaper.com/es/p/como-hacer-el-pollo-asado-perfecto</loc>
              <lastmod>2022-09-30T14:52:26.714Z</lastmod>
              <changefreq>monthly</changefreq>
              <priority>1.0</priority>
            </url><url>
              <loc>https://www.theaipaper.com/p/30-easy-and-healthy-dinner-recipes</loc>
              <lastmod>2022-09-30T14:52:26.467Z</lastmod>
              <changefreq>monthly</changefreq>
              <priority>1.0</priority>
            </url><url>
              <loc>https://www.theaipaper.com/es/p/30-recetas-de-cenas-faciles-y-saludables</loc>
              <lastmod>2022-09-30T14:52:26.467Z</lastmod>
              <changefreq>monthly</changefreq>
              <priority>1.0</priority>
            </url>
        
            <url>
              <loc>https://www.theaipaper.com/posts/1</loc>
              <lastmod>2022-09-30T14:52:26.467Z</lastmod>
              <changefreq>monthly</changefreq>
              <priority>1.0</priority>
            </url>
          
          
                <url>
                  <loc>https://www.theaipaper.com/es/posts/1</loc>
                  <lastmod>2022-09-30T14:52:26.467Z</lastmod>
                  <changefreq>monthly</changefreq>
                  <priority>1.0</priority>
                </url>
              
      </urlset>`